version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: python service_be/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    tty: true
    stdin_open: true

  web:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    command: npm start
    ports: 
      - "3000:3000"
    depends_on: 
      - api
    volumes: 
      - ./frontend-react/src:/frontend/src
    stdin_open: true
volumes:
  db-data: