# Generated by Django 3.1 on 2020-08-26 20:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.UUID('30e682ff-88ad-4c97-8d9d-8b9451944569'), max_length=256, primary_key=True, serialize=False),
        ),
    ]
