# Generated by Django 3.1 on 2020-08-26 13:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.CharField(default=uuid.UUID('41d6bde1-4ce9-4258-8b2a-ffcd2e08f0dd'), max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='id',
            field=models.CharField(default=uuid.UUID('98c06c02-bdba-4128-9ec0-7bb3f61a41dc'), max_length=256, primary_key=True, serialize=False),
        ),
    ]
