# Generated by Django 3.1 on 2020-08-26 20:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200826_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.UUID('c2fd38f9-0206-4882-86d7-d09685d9ba17'), max_length=256, primary_key=True, serialize=False),
        ),
    ]
