# Generated by Django 3.1 on 2020-08-26 19:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200826_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.CharField(default=uuid.UUID('4251e7a3-9eb3-477a-b071-08c283bbaa5d'), max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='id',
            field=models.CharField(default=uuid.UUID('c42bbf42-75fc-4b15-91f4-ab7b88a6e7db'), max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.UUID('fea717af-e83d-462c-a3ef-2c53cd7a6bdc'), max_length=256, primary_key=True, serialize=False),
        ),
    ]
