# Generated by Django 3.1 on 2020-08-29 20:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200829_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.UUID('1d229251-32bd-49b6-9b00-5cc2bb27c6ea'), max_length=256, primary_key=True, serialize=False),
        ),
    ]
