# Generated by Django 3.1 on 2020-08-26 19:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200826_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.CharField(default=uuid.UUID('cda3c584-f14b-4360-94f1-e8918a393584'), max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.UUID('0d9f53c0-6d20-43fd-b358-55c03aab05a0'), max_length=256, primary_key=True, serialize=False),
        ),
    ]
