# Generated by Django 3.1 on 2020-08-26 19:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200826_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.CharField(default=uuid.UUID('14252fd9-ec91-4a81-bd1b-49893a06ed0a'), max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.UUID('a151bc0a-a677-4b30-8f1d-3b3f71a6098e'), max_length=256, primary_key=True, serialize=False),
        ),
    ]
