# Generated by Django 3.1 on 2020-08-29 20:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200829_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.UUID('f64e5566-77ab-4623-9640-3ab73faac50e'), max_length=256, primary_key=True, serialize=False),
        ),
    ]
