# Generated by Django 3.1 on 2020-08-29 20:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200829_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='pay_type',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.UUID('6b5cfe17-be7e-4c8b-8790-3cc23701b306'), max_length=256, primary_key=True, serialize=False),
        ),
    ]
