# Generated by Django 3.1 on 2020-08-26 19:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200826_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.CharField(default=uuid.UUID('b84c4261-9b8d-4316-b944-b18fb4eb9c09'), max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.UUID('5de98fce-7836-44a8-9c5f-4d57cd04731a'), max_length=256, primary_key=True, serialize=False),
        ),
    ]
