# Generated by Django 3.1 on 2020-08-29 20:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200829_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='awarded_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awarded_to_proposal', to='main.proposal'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.UUID('793f714f-1939-4e76-8a64-10b3484746e1'), max_length=256, primary_key=True, serialize=False),
        ),
    ]
