# Generated by Django 3.1 on 2020-08-26 19:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200826_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.CharField(default=uuid.UUID('eb959afa-afb4-4fb6-a634-f3e3d258ea94'), max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.UUID('02afe9b6-d41c-420b-8038-917518d218df'), max_length=256, primary_key=True, serialize=False),
        ),
    ]
