# Generated by Django 3.1 on 2020-09-01 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200829_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='submitted_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='proposal',
            name='submitted_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
